# Numpy- Starting to Advance

### Importing Necessery Modules

In [1]:
import numpy as np
import pandas as pd

#### Difference Between Numpy Array & Python List

##### We can't make or do changes directly in python list but can in numpy array..

#### We can't directly do function in list so there is numpy comes. Another things that, List are slow as theire memory is high whether numpy are not slow rather it is super fast because of low memory..

## Making An Array

#### 1 Dimensional Array

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a = np.arange(25)
a
# It is arange(number of elements), not arrange.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
a.shape

# shape gives the value (number of elements, ).. (25,) be 

(25,)

In [5]:
type(a)

# ndarray means number of dimension of the array. Here it is 1 dimensional array.

numpy.ndarray

In [6]:
a.ndim

# Number of Dimension..

1

In [7]:
a.dtype

# Data Type is integer having 32 bits. 8 bits = 1 bytes.. Here it is 4 bytes

dtype('int32')

In [8]:
a.size

# It shows the number of elements the array having

25

In [9]:
np.zeros((3,4))

# (rows, columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((4,5), dtype = 'float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
a = np.random.rand(4,2)
a

array([[0.63014995, 0.87006325],
       [0.75135396, 0.90274202],
       [0.75323408, 0.14025718],
       [0.40239922, 0.83837515]])

In [12]:
np.random.random_sample(a.shape)

# It is like np.random.random_sample((4,2)) as a.shape is (4,2)

array([[0.4608277 , 0.65513374],
       [0.68128182, 0.21785641],
       [0.32762294, 0.01614826],
       [0.98904841, 0.4706503 ]])

In [13]:
np.random.randint(7, size = (3,3))

# 7 represent the number from 0 to 7 but not 7.

array([[0, 6, 1],
       [0, 6, 4],
       [2, 6, 0]])

#### Identity Array

In [14]:
np.identity(5)

# number of rows and columns. It should square matrix or array..

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [109]:
np.full_like(a.shape,4)

# full() and full_like() are same.. one is for shape uses others is for manual sizing..

array([4])

### Repeating an array to other array

In [114]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [116]:
r1 = np.repeat(arr, 4, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### Vertically Stacking Vectors

In [121]:
np.vstack([r1,arr])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [124]:
a = np.array([[1,2,3,4]])
b = np.array([[4,3,2,1]])

np.hstack([a,b])

array([[1, 2, 3, 4, 4, 3, 2, 1]])

In [125]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

#### Finding the element in 1D.

In [16]:
a = np.arange(-10,10)
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [17]:
a[10]

# It should return the value in the 10th position data which is 0

0

In [18]:
a[-2]

# From the last 2 position data which is 8

8

#### Replacing Value

In [19]:
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [20]:
a [11] = -1
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,  -1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [21]:
a[-5] = -12
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,  -1,   2,
         3,   4, -12,   6,   7,   8,   9])

#### Making an array with defiinig dtype

In [22]:
a = np.arange(-10, 10, 2, dtype = 'float32')
a

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.],
      dtype=float32)

### 2D Array

In [23]:
a = np.array([[1,20,3], [20,30,1]])
a

array([[ 1, 20,  3],
       [20, 30,  1]])

In [24]:
a [1,2] = 40
a

# a[row,columns] , count start from 0.

array([[ 1, 20,  3],
       [20, 30, 40]])

In [25]:
a.ndim

2

In [26]:
a = np.array([[12,14,15], [22,24,25]], dtype = 'float32')
a

array([[12., 14., 15.],
       [22., 24., 25.]], dtype=float32)

In [27]:
a = np.arange(24).reshape(2,12)
a

# reshape(rows, columns)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### 3D Array

In [28]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
a [:, 2:5]

# a[row, element position]
# a[:, 2:5] is all row and element of positioning 2 to 5 but not 5..

array([[ 2,  3,  4],
       [10, 11, 12],
       [18, 19, 20]])

In [30]:
a[1,2]

# 1 number of row and 2nd element. It is 10..

10

In [31]:
a[1:, 3:]

# It will return all the row from 1 to last and from 3 to last element

array([[11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23]])

### Multi Dimensional Array

In [32]:
a = np.arange(32).reshape(4,2,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [33]:
a.ndim

3

In [34]:
a = np.arange(32).reshape(4,2,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [35]:
a.ndim

4

In [36]:
a = np.arange(32).reshape(2,2,2,2,2)
a

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [37]:
a.ndim

5

## Mathematical terms

In [38]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(3,4)
a+b

# dimension have to be same

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [39]:
a = np.array([1,2,3,4])
b = np.array([12,2,12,12])
a+b

array([13,  4, 15, 16])

In [40]:
a*b

array([12,  4, 36, 48])

In [41]:
a/b

array([0.08333333, 1.        , 0.25      , 0.33333333])

In [ ]:
np.matmul(a,b)

In [42]:
np.sin(a)

# sin(a) here [sin(1),sin(2),sin(3),sin(4)]

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
np.cos(b)

array([ 0.84385396, -0.41614684,  0.84385396,  0.84385396])

In [44]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

##### cos(x), sin(x), cosec(x), sec(x), tan(x), cot(x)

## Indexing

In [45]:
a = np.array([[2,10,2], [11,20,3]])
a

array([[ 2, 10,  2],
       [11, 20,  3]])

In [46]:
a[1,2]

# a[row, column] ..It must be 3..

3

In [47]:
a[:, 1:]

# it must return all rows and element 1 to last..

array([[10,  2],
       [20,  3]])

In [48]:
a = np.arange(55).reshape(5,11)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [49]:
a[1:-1, 2:-2] = 99
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 99, 99, 99, 99, 99, 99, 99, 20, 21],
       [22, 23, 99, 99, 99, 99, 99, 99, 99, 31, 32],
       [33, 34, 99, 99, 99, 99, 99, 99, 99, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

## Slicing var[lower:upper:step]

In [50]:
a = np.arange(100).reshape(4,25)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
a[::2, 4::2]

array([[ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74]])

In [52]:
 a[:, 2]

array([ 2, 27, 52, 77])

## Copying a Array

##### If we dont use copy method, the array copied will be in same memory 

In [53]:
a = np.array([1,2,3,4])
b = a[:2]
b

array([1, 2])

In [54]:
b[0] = -10
b

array([-10,   2])

In [55]:
a

# that will also changes the previous main array, because it is in same memory..

array([-10,   2,   3,   4])

##### Copying by copy method

In [56]:
b = a.copy()
b

array([-10,   2,   3,   4])

In [57]:
b[2] = -20
b

array([-10,   2, -20,   4])

In [58]:
a

array([-10,   2,   3,   4])

In [59]:
a[1:] = [0,10,20]
a

array([-10,   0,  10,  20])

### Syntacting Sugar by __getitem__ 

In [60]:
# It is the fundamental of numpy array that works..

a.__getitem__(2)

# It is use in , a[2]..

10

In [61]:
a.__setitem__(1,-10)
a

# is the backbone of a[1] = -10

array([-10, -10,  10,  20])

In [62]:
a.__len__()

# is the backbone to len(a).

4

## Fancy Indexing / Booleans Indexing

In [63]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [64]:
position = [1,3,4,5]
y = a[position]
y

array([10, 30, 40, 50])

In [65]:
a[position] = 99
a

array([ 0, 99, 20, 99, 99, 99, 60, 70])

### Indexing with booleans

In [66]:
indexing = np.array([0,1,0,1,1,1,0,0], dtype = bool)
y = a[indexing]
y

array([99, 99, 99, 99])

In [67]:
a = np.array([-1,-3,1,4,-6,9,3])
a<0

array([ True,  True, False, False,  True, False, False])

In [68]:
negative = a<0
a[negative]

array([-1, -3, -6])

In [69]:
a[negative] = 0
a

# Replacing all negative with 0..

array([0, 0, 1, 4, 0, 9, 3])

#### Fancy Indexing in 2D

In [70]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
a[[0,1,2,3,4],[1,2,3,4,3]]

array([ 1,  7, 13, 19, 23])

In [72]:
a[3: , [0,2,4]]

array([[15, 17, 19],
       [20, 22, 24]])

## Array Calculation Methods

##### Not A Number nan

In [73]:
np.nan

nan

In [74]:
np.nan + 2

# Not a number so adding or replacing is also nan..

nan

In [75]:
a = np.arange(1,20,2).reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [76]:
a.sum()

100

In [77]:
a.mean()

# mean means average..

10.0

In [78]:
a.std()

# std means standard deviation

5.744562646538029

In [79]:
a.sum(axis = 0)

#axis 0 means row.. 1 is for column

array([12, 16, 20, 24, 28])

In [80]:
a.sum(axis = 1)

array([25, 75])

In [81]:
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [82]:
a.shape

(5, 6)

In [83]:
a.sum(axis = 0).shape
# Row is 5, column is 6, it return 6 meaning it has done sum of 5 row.. so it return 6..

(6,)

In [84]:
a.sum(axis = 1).shape

(5,)

In [85]:
a.prod()

# prod is for product..

1.0

In [86]:
a= np.arange(10,40,3).reshape(2,5)
a

array([[10, 13, 16, 19, 22],
       [25, 28, 31, 34, 37]])

In [87]:
a.max()

37

In [88]:
a.min()

10

In [89]:
a.ptp()

#ptp means pick to pick.. ptp means(max-min)

27

In [90]:
a.argmax()

# position of maximum value

9

In [91]:
a.argmin()

# position of min value..

0

In [92]:
a.var()

# variance as var

74.25

##### Truth Value Testing

In [93]:
a.all()

True

In [94]:
a.any()

True

In [95]:
np.unravel_index(a.argmax(), a.shape)

# find the max values exact position

(1, 4)

In [96]:
np.unravel_index(a.argmin(), a.shape)

(0, 0)

## Find by Where

#### Coordinate Location

In [97]:
a = np.arange(-2,2) **2
a

array([4, 1, 0, 1], dtype=int32)

In [98]:
mask = (a % 2 == 0)
mask

array([ True, False,  True, False])

In [99]:
np.where(mask)

(array([0, 2], dtype=int64),)

In [100]:
np.where(mask,1,0)

array([1, 0, 1, 0])

In [101]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.full((4,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [129]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])